// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";
import { defineConfig } from "prisma/config";

// Load .env.local first, then .env
// This ensures environment variables are loaded before Prisma uses them
const envLocal = config({ path: resolve(process.cwd(), ".env.local") });
const env = config({ path: resolve(process.cwd(), ".env") });

// Get DATABASE_URL from environment
const databaseUrl = process.env.DATABASE_URL || "";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
