import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    // Mobile-first breakpoints
    screens: {
      xs: "375px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      // ─── Brand Colors (typography system / design tokens) ──────────────
      colors: {
        "luxury-navy": {
          DEFAULT: "#0f172a",
          50: "#f0f3f9",
          100: "#d9e1f0",
          200: "#b3c3e0",
          300: "#7a95c7",
          400: "#4a6aac",
          500: "#2d4f93",
          600: "#1e3a7a",
          700: "#162c61",
          800: "#111f47",
          900: "#0f172a",
        },
        "luxury-cream": {
          DEFAULT: "#faf8f5",
          50: "#ffffff",
          100: "#faf8f5",
          200: "#f3ede6",
          300: "#e8ddd2",
          400: "#d4c4b0",
          500: "#bea98e",
        },
        "luxury-gold": {
          DEFAULT: "#c9a227",
          50: "#fdf9ec",
          100: "#f9edbe",
          200: "#f2d87a",
          300: "#e8c040",
          400: "#c9a227",
          500: "#a07f18",
          600: "#7a5f10",
        },
        // Keep existing token-based colors for compatibility
        brand: {
          bg: "var(--brand-bg)",
          primary: "var(--brand-primary)",
          secondary: "var(--brand-secondary)",
          text: "var(--brand-text)",
        },
        cream: {
          50: "var(--color-cream-50)",
          100: "var(--color-cream-100)",
          200: "var(--color-cream-200)",
          300: "var(--color-cream-300)",
          400: "var(--color-cream-400)",
          500: "var(--color-cream-500)",
          600: "var(--color-cream-600)",
          700: "var(--color-cream-700)",
          800: "var(--color-cream-800)",
          900: "var(--color-cream-900)",
        },
        charcoal: {
          50: "var(--color-charcoal-50)",
          100: "var(--color-charcoal-100)",
          200: "var(--color-charcoal-200)",
          300: "var(--color-charcoal-300)",
          400: "var(--color-charcoal-400)",
          500: "var(--color-charcoal-500)",
          600: "var(--color-charcoal-600)",
          700: "var(--color-charcoal-700)",
          800: "var(--color-charcoal-800)",
          900: "var(--color-charcoal-900)",
          950: "var(--color-charcoal-950)",
        },
        navy: {
          50: "var(--color-navy-50)",
          100: "var(--color-navy-100)",
          200: "var(--color-navy-200)",
          300: "var(--color-navy-300)",
          400: "var(--color-navy-400)",
          500: "var(--color-navy-500)",
          600: "var(--color-navy-600)",
          700: "var(--color-navy-700)",
          800: "var(--color-navy-800)",
          900: "var(--color-navy-900)",
          950: "var(--color-navy-950)",
        },
        forest: {
          50: "var(--color-forest-50)",
          100: "var(--color-forest-100)",
          200: "var(--color-forest-200)",
          300: "var(--color-forest-300)",
          400: "var(--color-forest-400)",
          500: "var(--color-forest-500)",
          600: "var(--color-forest-600)",
          700: "var(--color-forest-700)",
          800: "var(--color-forest-800)",
          900: "var(--color-forest-900)",
          950: "var(--color-forest-950)",
        },
        honey: {
          50: "var(--color-honey-50)",
          100: "var(--color-honey-100)",
          200: "var(--color-honey-200)",
          300: "var(--color-honey-300)",
          400: "var(--color-honey-400)",
          500: "var(--color-honey-500)",
          600: "var(--color-honey-600)",
        },
        blush: {
          50: "var(--color-blush-50)",
          100: "var(--color-blush-100)",
          200: "var(--color-blush-200)",
          300: "var(--color-blush-300)",
        },
        sage: {
          50: "var(--color-sage-50)",
          100: "var(--color-sage-100)",
          500: "var(--color-sage-500)",
          600: "var(--color-sage-600)",
        },
        dark: {
          bg: {
            primary: "var(--color-bg-primary, #0b0f1a)",
            secondary: "var(--color-bg-secondary, #0f1629)",
          },
          surface: {
            DEFAULT: "var(--color-surface, rgba(255, 255, 255, 0.08))",
            strong: "var(--color-surface-strong, rgba(255, 255, 255, 0.12))",
          },
          border: {
            glass: "var(--color-border-glass, rgba(255, 255, 255, 0.18))",
          },
          text: {
            primary: "var(--color-text-primary, #ffffff)",
            secondary: "var(--color-text-secondary, rgba(255, 255, 255, 0.7))",
            muted: "var(--color-text-muted, rgba(255, 255, 255, 0.45))",
          },
        },
        accent: {
          primary: "var(--accent-primary, #ff7a18)",
          secondary: "var(--accent-secondary, #ffd36b)",
          soft: "var(--accent-soft, rgba(255, 122, 24, 0.15))",
        },
        compact: {
          bg: {
            page: "var(--compact-bg-page, #f6f6f6)",
            surface: "var(--compact-bg-surface, #ffffff)",
            inverse: "var(--compact-bg-inverse, #121212)",
            subtle: "var(--compact-bg-subtle, #f1f1f1)",
          },
          text: {
            primary: "var(--compact-text-primary, #1e1e1e)",
            secondary: "var(--compact-text-secondary, #5e5e5e)",
            muted: "var(--compact-text-muted, #9a9a9a)",
            inverse: "var(--compact-text-inverse, #ffffff)",
          },
          border: {
            subtle: "var(--compact-border-subtle, #e6e6e6)",
            DEFAULT: "var(--compact-border-default, #dddddd)",
          },
          action: {
            primary: "var(--compact-action-primary, #ef1a14)",
            hover: "var(--compact-action-primary-hover, #d91611)",
            text: "var(--compact-action-primary-text, #ffffff)",
          },
          focus: {
            ring: "var(--compact-focus-ring, #111111)",
          },
        },
      },
      // Glassmorphism
      backgroundColor: {
        "glass": "rgba(255, 255, 255, 0.08)",
        "glass-strong": "rgba(255, 255, 255, 0.14)",
        "glass-subtle": "rgba(255, 255, 255, 0.04)",
        "glass-dark": "rgba(15, 23, 42, 0.6)",
        "glass-dark-strong": "rgba(15, 23, 42, 0.85)",
      },
      borderColor: {
        "glass": "rgba(255, 255, 255, 0.18)",
        "glass-strong": "rgba(255, 255, 255, 0.25)",
      },
      boxShadow: {
        "card-hover": "0 8px 32px rgba(15, 23, 42, 0.10)",
        sticky: "0 -1px 0 0 rgba(15, 23, 42, 0.06)",
        drawer: "-4px 0 24px rgba(15, 23, 42, 0.08)",
        dropdown: "0 8px 24px rgba(15, 23, 42, 0.10)",
        sm: "0 1px 3px rgba(28, 28, 28, 0.06)",
        md: "0 4px 12px rgba(28, 28, 28, 0.08)",
        lg: "0 8px 24px rgba(28, 28, 28, 0.08)",
        xl: "0 12px 40px rgba(28, 28, 28, 0.1)",
        navy: "0 4px 12px rgba(11, 31, 54, 0.25)",
        glass: "0 8px 32px rgba(0, 0, 0, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.1)",
        "glass-lg": "0 16px 48px rgba(0, 0, 0, 0.1), inset 0 1px 0 rgba(255, 255, 255, 0.12)",
        "glass-xl": "0 24px 64px rgba(0, 0, 0, 0.12), inset 0 1px 0 rgba(255, 255, 255, 0.14)",
        "luxury-gold": "0 4px 20px rgba(201, 162, 39, 0.25)",
        "luxury-gold-sm": "0 2px 8px rgba(201, 162, 39, 0.15)",
        "dark-soft": "var(--shadow-soft)",
        "dark-medium": "var(--shadow-medium)",
        "dark-strong": "var(--shadow-strong)",
        compact: "var(--compact-shadow-button, 0 4px 10px rgba(0, 0, 0, 0.08))",
        "compact-card": "var(--compact-shadow-card, 0 2px 8px rgba(0, 0, 0, 0.04))",
      },
      backdropBlur: {
        xs: "6px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        glass: "12px",
        "glass-lg": "24px",
      },
      maxWidth: {
        luxury: "1280px",
        content: "720px",
        "compact-mobile": "var(--compact-mobile-content-max, 320px)",
      },
      zIndex: {
        header: "100",
        drawer: "200",
        modal: "300",
        toast: "400",
      },
      borderRadius: {
        card: "12px",
        pill: "9999px",
        input: "8px",
        xs: "6px",
        sm: "10px",
        md: "var(--radius-card, 16px)",
        lg: "var(--radius-glass, 20px)",
        xl: "var(--radius-glass-lg, 24px)",
        glass: "16px",
        "glass-lg": "24px",
        "compact-sm": "var(--compact-radius-sm, 8px)",
        compact: "var(--compact-radius-md, 10px)",
        "compact-lg": "var(--compact-radius-lg, 12px)",
      },
      // Typography scale (design tokens) — display, headings, labels, body, price
      fontSize: {
        "display-lg": ["72px", { lineHeight: "1.0", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display": ["56px", { lineHeight: "1.05", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-sm": ["44px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "400" }],
        "h1": ["40px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "400" }],
        "h2": ["32px", { lineHeight: "1.2", letterSpacing: "-0.005em", fontWeight: "400" }],
        "h3": ["24px", { lineHeight: "1.3", letterSpacing: "0", fontWeight: "400" }],
        "label-lg": ["13px", { lineHeight: "1", letterSpacing: "0.14em", fontWeight: "600" }],
        "label": ["11px", { lineHeight: "1", letterSpacing: "0.12em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.7", fontWeight: "400" }],
        "body": ["16px", { lineHeight: "1.7", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "price-lg": ["24px", { lineHeight: "1", fontWeight: "600" }],
        "price": ["18px", { lineHeight: "1", fontWeight: "600" }],
        "price-sm": ["15px", { lineHeight: "1", fontWeight: "500" }],
        // Legacy / compatibility
        "phase-xs": ["var(--text-xs)", { lineHeight: "1.4" }],
        "phase-sm": ["var(--text-sm)", { lineHeight: "1.5" }],
        "phase-base": ["var(--text-base)", { lineHeight: "1.6" }],
        "phase-lg": ["var(--text-lg)", { lineHeight: "1.55" }],
        "phase-xl": ["var(--text-xl)", { lineHeight: "1.4" }],
        "phase-2xl": ["var(--text-2xl)", { lineHeight: "1.35" }],
        "phase-3xl": ["var(--text-3xl)", { lineHeight: "1.3" }],
        "phase-4xl": ["var(--text-4xl)", { lineHeight: "1.25" }],
        "phase-5xl": ["var(--text-5xl)", { lineHeight: "1.2" }],
        "caption": ["0.75rem", { lineHeight: "1.4", letterSpacing: "0.02em" }],
        "small": ["0.875rem", { lineHeight: "1.5", letterSpacing: "0.01em" }],
        "lead": ["1.125rem", { lineHeight: "1.55", letterSpacing: "0" }],
        "h4": ["1.25rem", { lineHeight: "1.4", letterSpacing: "-0.01em" }],
        "display-2xl": ["4.5rem", { lineHeight: "1.08", letterSpacing: "-0.02em" }],
        "display-xl": ["3.75rem", { lineHeight: "1.1", letterSpacing: "-0.02em" }],
        "display-md": ["2.25rem", { lineHeight: "1.3", letterSpacing: "-0.01em" }],
        "luxury-hero": ["clamp(2rem, 5vw, 4rem)", { lineHeight: "1.1", letterSpacing: "-0.03em" }],
        "luxury-title": ["clamp(1.5rem, 3vw, 2.5rem)", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        "compact-xs": ["var(--compact-font-xs, 11px)", { lineHeight: "var(--compact-lh-tight, 1.2)" }],
        "compact-sm": ["var(--compact-font-sm, 12px)", { lineHeight: "var(--compact-lh-tight, 1.2)" }],
        "compact-md": ["var(--compact-font-md, 14px)", { lineHeight: "var(--compact-lh-normal, 1.4)" }],
        "compact-lg": ["var(--compact-font-lg, 16px)", { lineHeight: "var(--compact-lh-tight, 1.2)" }],
        "compact-xl": ["var(--compact-font-xl, 20px)", { lineHeight: "var(--compact-lh-tight, 1.2)" }],
      },
      lineHeight: {
        "compact-tight": "var(--compact-lh-tight, 1.2)",
        "compact-normal": "var(--compact-lh-normal, 1.4)",
        "compact-relaxed": "var(--compact-lh-relaxed, 1.5)",
      },
      letterSpacing: {
        "compact-tight": "var(--compact-ls-tight, -0.01em)",
        "compact-normal": "var(--compact-ls-normal, 0em)",
        "compact-label": "var(--compact-ls-label, 0.08em)",
      },
      fontFamily: {
        playfair: ["Playfair Display", "Georgia", "serif"],
        inter: ["Inter", "system-ui", "sans-serif"],
        montserrat: ["Montserrat", "system-ui", "sans-serif"],
        serif: ["var(--font-playfair)", "Georgia", "serif"],
        sans: ["var(--font-sans)"],
      },
      // Spacing scale (8px base) + section tokens
      spacing: {
        "section-sm": "40px",
        "section": "64px",
        "section-lg": "96px",
        "section-xl": "128px",
        "container-x": "24px",
        "1": "var(--space-1)",
        "2": "var(--space-2)",
        "3": "var(--space-3)",
        "4": "var(--space-4)",
        "5": "var(--space-5)",
        "6": "var(--space-6)",
        "7": "var(--space-7)",
        "8": "var(--space-8)",
        "9": "var(--space-9)",
        "10": "var(--space-10)",
        "18": "4.5rem",
        "22": "5.5rem",
        "26": "6.5rem",
        "30": "7.5rem",
        "34": "8.5rem",
        "38": "9.5rem",
        "42": "10.5rem",
        "46": "11.5rem",
        "50": "12.5rem",
        "section-mobile": "var(--space-section-mobile, 4rem)",
        "section-tablet": "var(--space-section-tablet, 5rem)",
        "section-desktop": "var(--space-section-desktop, 6rem)",
        "section-hero": "var(--space-section-hero, 7rem)",
        "block": "var(--space-block, 1.5rem)",
        "inline": "var(--space-inline, 1rem)",
        "compact-1": "var(--compact-space-1, 4px)",
        "compact-2": "var(--compact-space-2, 8px)",
        "compact-3": "var(--compact-space-3, 12px)",
        "compact-4": "var(--compact-space-4, 16px)",
        "compact-5": "var(--compact-space-5, 20px)",
        "compact-6": "var(--compact-space-6, 24px)",
        "compact-8": "var(--compact-space-8, 32px)",
      },
      height: {
        "control-compact": "var(--compact-control-height, 42px)",
        "control-default": "var(--compact-control-height-default, 44px)",
      },
      transitionDuration: {
        "250": "250ms",
        "350": "350ms",
        "400": "400ms",
        fast: "150ms",
        normal: "300ms",
        slow: "500ms",
        "transition-fast": "120ms",
        "transition-base": "220ms",
        "transition-smooth": "400ms",
      },
      transitionTimingFunction: {
        luxury: "cubic-bezier(0.16, 1, 0.3, 1)",
        "out-soft": "cubic-bezier(0, 0, 0.2, 1)",
        "in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
        out: "cubic-bezier(0, 0, 0.2, 1)",
        in: "cubic-bezier(0.4, 0, 1, 1)",
        "transition-smooth": "cubic-bezier(0.16, 1, 0.3, 1)",
        "luxury-ease": "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        compact: "var(--compact-motion-easing, cubic-bezier(0.2, 0, 0, 1))",
      },
      // Custom animations (luxury + existing)
      animation: {
        "fade-in": "fadeIn 0.6s ease-in-out",
        "fade-in-up": "fadeInUp 0.6s ease-out",
        "fade-in-down": "fadeInDown 0.6s ease-out",
        "slide-in-right": "slideInRight 0.6s ease-out",
        "slide-in-left": "slideInLeft 0.6s ease-out",
        "scale-in": "scaleIn 0.4s ease-out",
        "smooth-float": "smoothFloat 3s ease-in-out infinite",
        shimmer: "shimmer 2s linear infinite",
        "luxury-fade-in": "luxuryFadeIn 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards",
        "luxury-slide-up": "luxurySlideUp 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards",
        "luxury-scale": "luxuryScale 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeInDown: {
          "0%": { opacity: "0", transform: "translateY(-20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        smoothFloat: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        luxuryFadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        luxurySlideUp: {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        luxuryScale: {
          "0%": { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    require("@tailwindcss/aspect-ratio"),
  ],
};

export default config;
